#spotify_user_id = ""
#sp_dc = ""
#sp_key = ""
playlists_public = false

enable_cache = false
redis_host = "localhost"
redis_port = "6379"
redis_db = "0"

playlist_ids_file = "playlist_ids.json"

log_level_debug = true